# This workflow will install dependencies, create coverage tests and run Pytest Coverage Comment
# For more information see: https://github.com/MishaKav/pytest-coverage-comment/
name: pytest-coverage-comment
on:
  pull_request:
    branches:
      - '*'

# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
# `contents` is for permission to the contents of the repository.
# `pull-requests` is for permission to pull request
permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12

      - name: Install poetry
        run: python -m pip install poetry

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          poetry install --no-root

      - name: Build coverage file
        run: |
          poetry run pytest --junitxml=./reports/pytest.xml --cov-report=term-missing:skip-covered --cov=src tests/ | tee ./reports/pytest-coverage.txt

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./reports/pytest-coverage.txt
          pytest-xml-coverage-path: ./reports/
          junitxml-path: ./reports/pytest.xml