
env:
  POETRY_VERSION: 1.6.0

# This workflow will install dependencies, create coverage tests and run Pytest Coverage Comment
# For more information see: https://github.com/MishaKav/pytest-coverage-comment/
name: pytest-coverage-comment
on:
  pull_request:
    branches:
      - '*'

# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
# `contents` is for permission to the contents of the repository.
# `pull-requests` is for permission to pull request
permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12

      - name: Install poetry
        run: python -m pip install poetry

      - name: Install Poetry
        run: python -m pip install poetry==$POETRY_VERSION

      - name: Install dependencies with Poetry
        run: |
          poetry install

      - name: Build coverage file
        run: |
          poetry run pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=src/otterseq tests/ | tee pytest-coverage.txt

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          pytest-xml-coverage-path: ./
          junitxml-path: ./pytest.xml